InformationForBeamlines facade update
synchrotron-solaris/dev-solaris-informationforbl pull request #2
Opened 2017-07-31 07:03 UTC by cpt-majkel

closes #1 
Updated InformationForBeamlines facade
Added autogenerated documentation in Sphinx

2017-07-31 08:46 UTC, LJBD requested changes

2017-07-31 08:46 UTC, LJBD commented on information_for_beamlines_ds/__init__.py
> +This package contains InformationForBeamlines device class based on the facadedevice library. It stores communication between Control Room and beamlines.
This line looks longer than 80 characters.

2017-07-31 08:46 UTC, LJBD commented on information_for_beamlines_ds/__init__.py
> +for package_name in find_packages():
I don't think this loop is necessary here.

2017-07-31 08:46 UTC, LJBD commented on information_for_beamlines_ds/information_for_beamlines.py
> +"""This is the InformationForBeamlines device based on the facadedevice library. It stores communication between Control Room and beamlines."""
This line looks longer than 80 characters.

2017-07-31 08:46 UTC, LJBD commented on information_for_beamlines_ds/information_for_beamlines.py
> +    def BeamCurrent_mA(self, data):
Please remove the `BeamCurrent_mA` attribute and include the calculation in the `BeamCurrent` attribute.
We want to have only one attribute, called `BeamCurrent` which displays beam current in milliamperes.

2017-07-31 08:46 UTC, LJBD commented on information_for_beamlines_ds/information_for_beamlines.py
> +    def always_executed_hook(self):
Please remove this method.

2017-07-31 08:46 UTC, LJBD commented on information_for_beamlines_ds/information_for_beamlines.py
> +    def delete_device(self):
Please remove this method.

2017-07-31 08:46 UTC, LJBD commented on information_for_beamlines_ds/information_for_beamlines.py
> +    def state_from_data(self, data):
Please update this method so that it uses `@state_attribute` decorator.

2017-07-31 08:46 UTC, LJBD commented on information_for_beamlines_ds/information_for_beamlines.py
> +        # self.push_change_event('GeneralInfo')
Please uncomment those lines and find a way to configure pushing events for this attribute from the code.
This also applies to the `FillingPattern` attribute.

2017-07-31 08:47 UTC, LJBD commented on information_for_beamlines_ds/information_for_beamlines.py
> +class InformationForBeamlines(Facade):
Please add a class docstring.

2017-07-31 13:54 UTC, cpt-majkel commented
I got rid of the errors in GeneralInfo and FillingPattern write methods - there was a problem with arguments. User is now able to type in some text and it will be shown properly in Jive. I am not sure however, if it is because of push_change_event or simply because of `self.general_info = value` assignment.

2017-07-31 13:57 UTC, LJBD requested changes

2017-07-31 13:57 UTC, LJBD commented on information_for_beamlines_ds/__init__.py
> +package_name=find_packages()
My idea was to remove this part of `__init__.py` completely, not to remove the `for` statement only 😃

2017-07-31 13:57 UTC, LJBD commented on information_for_beamlines_ds/information_for_beamlines.py
>          self.set_status('Everything is OK.')
I think that `@state_attribute` should return state and status, not set them...

2017-07-31 13:57 UTC, LJBD commented on information_for_beamlines_ds/information_for_beamlines.py
> +        self.push_data_ready_event('FillingPattern', 0)
Please check subscription to these attributes (you'll only see events appearing after writing something to these attributes).

2017-07-31 14:00 UTC, LJBD commented
@cpt-majkel - as I've noted in my comments to the PR: please test the events for those attributes. You can do it like I've shown you:
```python
dev = tango.DeviceProxy('info/for/bl1')
ev_id = dev.subscribe_event('GeneralInfo`, tango.EventType.CHANGE_EVENT, tango.utils.EventCallBack())
# the first event should appear on its own, the rest after you write something to the attribute
dev.unsubscribe_event(ev_id)
```

2017-08-01 08:19 UTC, cpt-majkel commented on information_for_beamlines_ds/information_for_beamlines.py
> +        self.push_data_ready_event('FillingPattern', 0)
Ok, now everything seems to be working. After writing something to the attributes, `change_event` is pushed.

![testevents](https://user-images.githubusercontent.com/24622343/28815703-85010b4e-76a2-11e7-9021-88828f7cbe2d.png)

2017-08-01 12:10 UTC, LJBD approved these changes

2017-08-01 13:08 UTC, merged